SOAP MONITOR ADDED
site24x7/terraform-provider-site24x7 pull request #314
Opened 2024-10-23 09:31 UTC by sujithramagesh

2024-10-24 17:35 UTC, JasperPaul requested changes
Given comments

2024-10-24 17:35 UTC, JasperPaul commented on docs/resources/soap_monitor.md
> +page_title: "Site24x7: site24x7_port_monitor"
Why port monitor for soap_monitor.md?

2024-10-24 17:35 UTC, JasperPaul commented on docs/resources/soap_monitor.md
> +  Create and manage a PING monitor in Site24x7.
written as ping monitor here...????

2024-10-24 17:35 UTC, JasperPaul commented on docs/resources/soap_monitor.md
> +# Resource: site24x7\_ping\_monitor
Correct the names @sujithramagesh

2024-10-24 17:35 UTC, JasperPaul commented on site24x7/monitors/soap.go
> +	d.Set("use_ipv6", monitor.UseIPV6)
ipv4 is not there? @sujithramagesh

2024-10-25 05:26 UTC, sujithramagesh commented on site24x7/monitors/soap.go
> +	d.Set("use_ipv6", monitor.UseIPV6)
if use_ipv6 is false then it is ipv4

2024-10-25 07:05 UTC, closed without merging